version: '3.8'
services:
  apprentissage_production:
    build: .
    volumes:
      - .:/app
    command:
      - /bin/bash
      - -c
      - |
        python -m src.ia
        python -m src.app
    ports:
      - 5000:5000